const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='mmn_records_v1'; let records=JSON.parse(localStorage.getItem(KEY)||'[]'); let current=records[0]||null; let sound=false;
const causes=['മനുഷ്യന്റെ കൈ','കൊതുക് ബാറ്റ്','ചെരിപ്പ്','ഇൻസെക്ടിസൈഡ്','അറിയില്ല','മറ്റുള്ളവ'];
function save(){localStorage.setItem(KEY,JSON.stringify(records));}
function id(){return 'MMN-2026-'+String(records.length+482).padStart(5,'0')}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function particles(el,n=70){for(let i=0;i<n;i++){let p=document.createElement('i');p.className='p';p.style.left=Math.random()*100+'%';p.style.top=Math.random()*100+'%';p.style.animationDuration=(6+Math.random()*10)+'s';p.style.animationDelay=(-Math.random()*10)+'s';el.appendChild(p)}}
particles($('#introParticles'),85);
function render(){let r=location.hash.slice(1)||'home'; const routes={home:home,report:report,memorials:memorials,cemetery:cemetery,csi:csi,dashboard:dashboard,profile:profile,certificate:certificate,family:family,condolence:condolence,chat:chat,funeral:funeral,court:court}; (routes[r]||home)(); $$('.nav nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===r)); window.scrollTo({top:0,behavior:'smooth'});}
function shell(title,sub,body){$('#view').innerHTML=`<section class="page"><div class="section-title"><span class="kicker">MMN // DEPARTMENT</span><h1>${title}</h1><p>${sub}</p></div>${body}</section>`;bind()}
function home(){const nums=[1284,642,317];shell('ആരുടെയോ കുടുംബം കാത്തിരിക്കുന്നു.','ഒരു കൊതുകിന്റെ മരണം റിപ്പോർട്ട് ചെയ്യൂ. അവന്റെ കുടുംബത്തെ കണ്ടെത്തൂ. അവന് അർഹമായ യാത്രയയപ്പ് നൽകൂ.',`<div class="hero"><div class="hero-content"><span class="kicker">MMN // ACTIVE NETWORK</span><h1>ആരുടെയോ കുടുംബം<br>കാത്തിരിക്കുന്നു.</h1><p>ഒരു കൊതുകിന്റെ മരണം റിപ്പോർട്ട് ചെയ്യൂ. അവന്റെ കുടുംബത്തെ കണ്ടെത്തൂ. അവന് അർഹമായ യാത്രയയപ്പ് നൽകൂ.</p><div class="actions"><a class="primary" href="#report">മരണം റിപ്പോർട്ട് ചെയ്യുക →</a><a class="secondary" href="#memorials">മെമ്മോറിയൽ സന്ദർശിക്കുക</a></div><div class="network"><div class="net-intro"><b>MMN NETWORK STATUS</b><div class="online">● ONLINE</div></div>${[['Registered Mosquitoes','1,284'],['Memorials','642'],['Families Located','317'],['Uselessness Score','99.8%']].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></div></div>`)}
function report(){shell('ഈ കൊതുക് എങ്ങനെയാണ് ഈ ലോകം വിട്ടത്?','ഒരു ഔദ്യോഗിക മരണ റിപ്പോർട്ട് സമർപ്പിക്കുക.',`<form id="reportForm" class="glass form-card"><div class="form-grid"><div class="field full"><label>കൊതുകിന്റെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക</label><label class="upload" for="photo"><span id="uploadText">Drag & drop / തിരഞ്ഞെടുക്കുക<br><small>JPG, PNG</small></span><img id="preview" class="hidden"></label><input id="photo" type="file" accept="image/*" hidden></div><div class="field"><label>പേര്</label><input id="name" required placeholder="ഉദാ: കുഞ്ഞുമോൾ"></div><div class="field"><label>മരണ തീയതി</label><input id="date" type="date" required></div><div class="field full"><label>കൂടുതൽ വിവരങ്ങൾ</label><textarea id="details" placeholder="സംഭവത്തെക്കുറിച്ച് കുറച്ച് വിവരങ്ങൾ…"></textarea></div><div class="field full"><label>മരണ കാരണം</label><div class="causes">${causes.map((c,i)=>`<button type="button" class="cause ${i===1?'selected':''}" data-cause="${c}">${c}</button>`).join('')}</div></div></div><div class="form-footer"><span class="step">01 / 01 — REPORT</span><button class="primary">റിപ്പോർട്ട് സമർപ്പിക്കുക →</button></div></form>`);let selected='കൊതുക് ബാറ്റ്'; $$('.cause').forEach(b=>b.onclick=()=>{$$('.cause').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.cause}); $('#photo').onchange=e=>previewFile(e.target.files[0]); $('#reportForm').onsubmit=e=>{e.preventDefault();let rec={id:id(),name:$('#name').value,date:$('#date').value,details:$('#details').value,cause:selected,image:$('#preview').src||'',species:'Culex-type Mosquito',confidence:'94.7%',age:'Unknown',family:'Buzzington',status:'Departed',condolences:[],verdict:null};records.unshift(rec);current=rec;save();toast('മരണ റിപ്പോർട്ട് രജിസ്റ്റർ ചെയ്തു. '+rec.id);location.hash='analysis';analysis()};}
function previewFile(f){if(!f)return;let reader=new FileReader();reader.onload=()=>{$('#preview').src=reader.result;$('#preview').classList.remove('hidden');$('#uploadText').classList.add('hidden')};reader.readAsDataURL(f)}
function analysis(){if(!current)return location.hash='report';shell('AI പരിശോധന പുരോഗമിക്കുന്നു…','Demo analysis — യഥാർത്ഥ AI model ഇല്ലെങ്കിൽ ഫലം simulated ആയി കണക്കാക്കുക.',`<div class="glass scan"><div class="scan-ring"><div></div></div><h2 id="scanText">IMAGE INGESTION</h2><p id="scanSub" class="muted">Visual evidence is being classified…</p><div id="analysisResult" class="hidden"><h2>AI പരിശോധന പൂർത്തിയായി!</h2><div class="result-grid">${[['Species','Culex-type Mosquito'],['Confidence','94.7%'],['Wing Analysis','2 wings detected'],['Leg Count','6'],['Cause of Death',current.cause],['Mode','Simulated / Demo']].map(x=>`<div class="result"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="actions"><a class="primary" href="#profile">പ്രൊഫൈൽ കാണുക →</a></div></div></div>`);let texts=['IMAGE INGESTION','WING ANALYSIS','SPECIES CLASSIFICATION','CAUSE CORRELATION','FINALIZING REPORT'];let i=0;let timer=setInterval(()=>{$('#scanText').textContent=texts[i++]||'COMPLETE';if(i>texts.length){clearInterval(timer);$('#scanSub').textContent='Demo result generated locally. No real AI inference was performed.';$('#analysisResult').classList.remove('hidden')}},650)}
function profile(){if(!current)return empty('ഒരു record തിരഞ്ഞെടുക്കുക.');shell('Mosquito Profile','ഒരു ഔദ്യോഗിക MMN identity.',`<div class="profile"><div class="glass portrait">${current.image?`<img src="${current.image}" alt="${current.name} uploaded mosquito image">`:'<div class="placeholder">🦟</div>'}</div><div class="glass form-card"><span class="id">${current.id}</span><h2>${current.name}</h2><div class="chips"><span class="chip">${current.species}</span><span class="chip">Age: ${current.age}</span><span class="chip">${current.status}</span><span class="chip">Family: ${current.family}</span></div><div class="result-grid"><div class="result"><span>Departure</span><b>${current.date}</b></div><div class="result"><span>Cause</span><b>${current.cause}</b></div></div><div class="actions"><a class="primary" href="#certificate">Death Certificate</a><a class="secondary" href="#family">Family കണ്ടെത്തുക</a><a class="secondary" href="#memorials">Memorial കാണുക</a></div></div></div>`)}
function certificate(){if(!current)return empty('No record.');shell('കൊതുകിന്റെ യാത്രയയപ്പ് സർട്ടിഫിക്കറ്റ്','Print-friendly official document.',`<div class="glass certificate" id="certificatePrint"><div class="seal">MMN<br>OFFICIAL</div><h2>കൊതുകിന്റെ യാത്രയയപ്പ് സർട്ടിഫിക്കറ്റ്</h2><p>THIS CERTIFIES THAT</p><h3>${current.name}</h3><p class="id">${current.id}</p><div class="result-grid">${[['Species',current.species],['Date of Departure',current.date],['Cause of Death',current.cause],['Final Words','“അവന്റെ buzz എന്നും ഓർമ്മിക്കപ്പെടും.”']].map(x=>`<div class="result"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><p style="margin-top:30px;color:#94A3B8">Mosquito Mourning Network</p></div><div class="actions"><button class="primary" id="printCert">Download / Print PDF</button></div>`);$('#printCert').onclick=()=>window.print()}
function family(){if(!current)return empty('No record.');shell('കുടുംബത്തെ കണ്ടെത്തുന്നു…','Family identification protocol completed.',`<div class="glass family"><h2>കുടുംബബന്ധം സ്ഥിരീകരിച്ചു.</h2><p class="id">${current.family.toUpperCase()} FAMILY</p><div class="tree"><div class="tree-row"><div class="member">Grandmother Mosquita<small>Grandmother</small></div><div class="member">Family Lawyer<small>Legal</small></div></div><div class="tree-row"><div class="member">Father Buzzington<small>Father</small></div><div class="member">Mother Mosquita<small>Mother</small></div></div><div class="tree-row"><div class="member">${current.name}<small>Departed</small></div><div class="member">Brother Buzz<small>Brother</small></div><div class="member">Cousin Wings<small>Cousin</small></div></div></div></div><div class="glass form-card" style="margin-top:15px"><h3>കുടുംബത്തെ വിവരം അറിയിച്ചു.</h3><div class="notice"><div class="result"><b>ബന്ധം സ്ഥിരീകരിച്ചു.</b></div><div class="result"><b>സ്വാം കുടുംബത്തെ കണ്ടെത്തി.</b></div><div class="result"><b>അമ്മായി Mosquita-യെ ബന്ധപ്പെട്ടു.</b></div></div><div class="actions"><a class="primary" href="#condolence">അനുശോചനം രേഖപ്പെടുത്തുക</a><a class="secondary" href="#chat">AI Family Chat</a></div></div>`)}
function condolence(){if(!current)return empty('No record.');shell('കുടുംബത്തോട് അനുശോചനം രേഖപ്പെടുത്തുക.','Your message will appear on the memorial.',`<div class="glass form-card"><form id="condForm"><div class="field"><label>Message</label><textarea id="condText" required placeholder="അവന്റെ buzz എന്നും ഓർമ്മിക്കപ്പെടും."></textarea></div><div class="actions"><button class="primary">അനുശോചനം അയയ്ക്കുക →</button></div></form></div><div class="glass form-card" style="margin-top:15px"><h3>Recent Condolences</h3><div id="condList">${(current.condolences||[]).map(x=>`<div class="msg ai">${esc(x)}</div>`).join('')||'<p style="color:#94A3B8">ഇവിടെ ആദ്യത്തെ സന്ദേശം നിങ്ങളുടേതാകാം.</p>'}</div></div>`);$('#condForm').onsubmit=e=>{e.preventDefault();current.condolences=current.condolences||[];current.condolences.unshift($('#condText').value);save();toast('അനുശോചനം രേഖപ്പെടുത്തി.');condolence()}}
function chat(){if(!current)return empty('No record.');shell('AI Family Chat','Choose a character and ask something. Responses are predefined when no external AI API exists.',`<div class="glass chat"><div class="messages" id="messages"><div class="msg ai"><b>അമ്മായി Mosquita</b><br>നഷ്ടം വളരെ വലുതാണ്… പക്ഷേ അവന്റെ buzz എന്നും ഓർമ്മിക്കപ്പെടും.</div></div><div class="chatbar"><select id="character"><option>അമ്മായി Mosquita</option><option>അച്ഛൻ Buzzington</option><option>സഹോദരൻ Buzz</option><option>Family Lawyer</option></select><input id="chatInput" placeholder="അവൻ എങ്ങനെയായിരുന്നു?"><button class="primary" id="sendChat">Send</button></div></div>`);$('#sendChat').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()}}
function sendChat(){let input=$('#chatInput');if(!input.value.trim())return;let text=input.value.trim(), char=$('#character').value, m=$('#messages');m.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(text)}</div>`);input.value='';let reply=char.includes('Lawyer')?'കേസ് ഫയൽ ചെയ്തിട്ടുണ്ട്. വികാരപരമായി പ്രതികരിക്കുന്നത് എന്റെ scope-ൽ ഇല്ല… പക്ഷേ നഷ്ടപരിഹാരത്തെക്കുറിച്ച് സംസാരിക്കാം.':char.includes('Mother')||char.includes('Mosquita')?'വളരെ സ്നേഹമുള്ള കൊതുകായിരുന്നു… എല്ലാവരെയും കടിക്കുമായിരുന്നു.':'അവൻ ഒരു സാധാരണ buzz അല്ലായിരുന്നു. വളരെ പ്രത്യേകതയുണ്ടായിരുന്നു.';setTimeout(()=>{m.insertAdjacentHTML('beforeend',`<div class="msg ai"><b>${char}</b><br>${reply}</div>`);m.scrollTop=m.scrollHeight},450)}
function funeral(){if(!current)return empty('No record.');shell('സ്നേഹപൂർവ്വം ഓർക്കുന്നു','A ceremonial farewell.',`<div class="glass funeral"><div><span class="kicker">MMN MEMORIAL CEREMONY</span><h1>${current.name}</h1><p>${current.family} · ${current.date}</p><button class="primary" id="startFuneral">യാത്രയയപ്പ് ആരംഭിക്കുക</button><div id="funeralText" class="hidden"></div></div></div>`);$('#startFuneral').onclick=()=>{let lines=['അവന്റെ ചെറിയ ചിറകുകൾ ഇനി നിശ്ചലമാണ്.','എന്നാൽ അവന്റെ buzz…','ഒരിക്കലും മറക്കപ്പെടില്ല.'];let i=0;$('#startFuneral').classList.add('hidden');let box=$('#funeralText');box.classList.remove('hidden');let t=setInterval(()=>{box.innerHTML=`<p style="font-size:25px;color:white">${lines[i++]}</p>`;if(i===lines.length){clearInterval(t);setTimeout(()=>location.hash='memorials',1200)}},1400)} }
function memorials(){shell('ഓർമ്മകൾ ഇവിടെ തുടരുന്നു.','Memorial registry.',`<div class="filters"><input id="memSearch" placeholder="Search memorials…"></div><div id="memGrid">${records.length?records.map(card).join(''):emptyCard()}</div>`);$('#memSearch').oninput=e=>{$('#memGrid').innerHTML=records.filter(r=>r.name.toLowerCase().includes(e.target.value.toLowerCase())).map(card).join('')||emptyCard();bindCards()};bindCards()}
function card(r){return `<div class="glass form-card" style="margin-bottom:14px;display:flex;justify-content:space-between;gap:20px;align-items:center"><div><span class="id">${r.id}</span><h3>${r.name}</h3><p style="color:#94A3B8">${r.species} · ${r.cause}</p></div><div class="actions"><button class="secondary" data-open="${r.id}">View Memorial</button></div></div>`}function emptyCard(){return '<div class="glass form-card"><p style="color:#94A3B8">ഇപ്പോൾ memorials ഒന്നുമില്ല. ഒരു മരണ റിപ്പോർട്ട് സമർപ്പിക്കൂ.</p></div>'}function bindCards(){$$('[data-open]').forEach(b=>b.onclick=()=>{current=records.find(r=>r.id===b.dataset.open);location.hash='profile'})}
function cemetery(){shell('കൊതുക് സെമിത്തേരി','A quiet digital cemetery for departed mosquitoes.',`<div class="glass cemetery"><div class="filters"><input id="cemSearch" placeholder="Search by name…"><select id="cemCause"><option value="">All causes</option>${causes.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="graveyard" id="graveyard">${records.map(grave).join('')||'<p style="color:#94A3B8">സെമിത്തേരി ഇപ്പോൾ ശൂന്യമാണ്.</p>'}</div></div>`);const filter=()=>{let q=$('#cemSearch').value.toLowerCase(),c=$('#cemCause').value;$('#graveyard').innerHTML=records.filter(r=>(!q||r.name.toLowerCase().includes(q))&&(!c||r.cause===c)).map(grave).join('')||'<p style="color:#94A3B8">No graves found.</p>';bindGraves()};$('#cemSearch').oninput=filter;$('#cemCause').onchange=filter;bindGraves()}
function grave(r){return `<div class="grave" data-open="${r.id}"><b>${r.name}</b><span>${r.date}</span><span>${r.cause}</span></div>`}function bindGraves(){$$('.grave').forEach(g=>g.onclick=()=>{current=records.find(r=>r.id===g.dataset.open);location.hash='profile'})}
function csi(){let r=current||records[0]||{id:'MMN-CSI-00482',cause:'കൊതുക് ബാറ്റ്'};shell('MMN CSI','Forensic investigation department.',`<div class="glass form-card"><span class="status">CASE OPEN</span><h2>${r.id.replace('MMN','MMN-CSI')}</h2><div class="evidence">${[['Wing Damage','Moderate'],['Body Condition','Impact consistent'],['Impact Pattern',r.cause],['Blood Evidence','Inconclusive'],['Environmental Evidence','Human surroundings'],['Classification','Human Intervention']].map(x=>`<div class="result"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="actions"><button class="primary" id="closeCase">CASE CLOSED</button></div></div>`);$('#closeCase').onclick=()=>{toast('CASE CLOSED — investigation archived.');$('#closeCase').textContent='CASE CLOSED ✓';$('#closeCase').disabled=true}}
function court(){if(!current)return empty('Report a mosquito first.');shell('കൊതുക് കോടതി','The people vs. whoever did it.',`<div class="court"><div class="glass form-card"><span class="status">CASE ${current.id}</span><h2>Charges</h2><ul><li>Illegal mosquito termination</li><li>Unnecessary violence</li><li>Wing destruction</li></ul><h3>Evidence</h3><p style="color:#94A3B8">Cause reported: ${current.cause}</p><h3>Witness</h3><p>Neighbouring mosquito colony.</p></div><div class="glass verdict" id="verdict"><h2>Verdict</h2><p>Choose the ruling.</p><div class="actions" style="justify-content:center"><button class="primary" id="guilty">GUILTY</button><button class="secondary" id="notGuilty">NOT GUILTY</button></div></div></div>`);$('#guilty').onclick=()=>setVerdict('GUILTY');$('#notGuilty').onclick=()=>setVerdict('NOT GUILTY')}
function setVerdict(v){current.verdict=v;save();$('#verdict').className='glass verdict '+(v==='GUILTY'?'guilty':'not');$('#verdict').innerHTML=`<h2>Verdict</h2><div class="big-verdict">${v}</div><p>കൊതുക് കോടതി വിധി രേഖപ്പെടുത്തി.</p><button class="secondary" onclick="location.hash='dashboard'">Dashboard →</button>`;toast('Verdict saved.')}
function dashboard(){let all=records.reduce((a,r)=>a+r.condolences?.length||0,0);shell('MMN Uselessness Dashboard','A completely serious measurement system.',`<div class="dashboard-grid"><div class="glass dash"><strong>${1284+records.length}</strong><span>Mosquitoes mourned</span></div><div class="glass dash"><strong>${317+records.length}</strong><span>Families contacted</span></div><div class="glass dash"><strong>${642+records.length}</strong><span>Funerals conducted</span></div><div class="glass dash"><strong>${3904+all}</strong><span>Condolences</span></div><div class="glass dash"><strong>${128+records.filter(r=>r.verdict).length}</strong><span>Court cases</span></div><div class="glass dash"><strong>0</strong><span>Actual problems solved</span></div><div class="glass dash useless"><strong>99.8%</strong><span>Uselessness Score</span><div class="bar"><i></i></div></div></div><div class="glass form-card" style="margin-top:15px;text-align:center"><h2>Congratulations.</h2><p style="color:#94A3B8">You have successfully contributed absolutely nothing to society.</p><div class="actions" style="justify-content:center"><a class="primary" href="#home">Return to MMN</a></div></div>`)}
function empty(msg){shell('MMN','',`<div class="glass form-card"><p>${msg}</p><a class="primary" href="#report">Report Death →</a></div>`)}
function bind(){}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#enterBtn').onclick=()=>{localStorage.setItem('mmn_intro_seen','1');$('#intro').classList.add('exit');setTimeout(()=>{$('#intro').remove();$('#app').classList.remove('hidden');location.hash='home'},900)};
$('#skipBtn').onclick=()=>{$('#enterBtn').click()};$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'◉ ON':'◉';toast(sound?'Ambient sound enabled (demo control).':'Sound off.')};$('#replayIntro').onclick=()=>{location.reload()};
if(localStorage.getItem('mmn_intro_seen')){$('#intro').remove();$('#app').classList.remove('hidden')}else setTimeout(()=>{$('#introBrand').style.opacity=1;$('#introBrand').style.transform='none';$('#enterBtn').disabled=false},5000);
window.addEventListener('hashchange',()=>{if(location.hash==='#analysis')analysis();else render()}); if(!location.hash&&localStorage.getItem('mmn_intro_seen'))location.hash='home'; if(location.hash&&location.hash!=='#analysis')render();
</script>
</body></html>
